//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace son
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunler
    {
        public int Id { get; set; }
        public string BRAND { get; set; }
        public string MODEL { get; set; }
        public long CAPACITY { get; set; }
        public int PLATE { get; set; }
        public string TYPE { get; set; }
        public System.DateTime MODEL_YEAR { get; set; }
        public string COLOR { get; set; }
    }
}
